// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, http, logs, port, server, vartable;

  express = require('express');

  http = require('http');

  app = express();

  server = http.createServer(app);

  app.use(express["static"](__dirname + '/'));

  app.use(express.json());

  vartable = {};

  app.get('/varTable', function(req, res) {
    var varname;
    varname = req.query['varname'];
    if (varname == null) {
      res.send(JSON.stringify(vartable));
      return;
    }
    if (req.query['set'] != null) {
      vartable[varname] = req.query['set'];
    }
    return res.send(vartable[varname]);
  });

  logs = [];

  app.get('/getlogs', function(req, res) {
    var user;
    user = req.query.user;
    if (user == null) {
      res.send('need user parameter');
      return;
    }
    return res.send(logs[user]);
  });

  app.post('/postlog', function(req, res) {
    var data, user;
    data = req.body;
    console.log(data);
    if (data.user == null) {
      return;
    }
    user = data.user;
    if (logs[user] == null) {
      logs[user] = [];
    }
    return logs[user].push(data);
  });

  port = Number(process.env.PORT || 8080);

  server.listen(port);

  console.log("Server running on port " + (server.address().port));

}).call(this);
