// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, http, server, vartable;

  express = require('express');

  http = require('http');

  app = express();

  server = http.createServer(app);

  app.use(express["static"](__dirname + '/'));

  vartable = {};

  app.get('/varTable', function(req, res) {
    var varname;
    varname = req.query['varname'];
    if (varname == null) {
      res.send(JSON.stringify(vartable));
      return;
    }
    if (req.query['set'] != null) {
      vartable[varname] = req.query['set'];
    }
    return res.send(vartable[varname]);
  });

  server.listen(8080);

  console.log("Server running on port " + (server.address().port));

}).call(this);
