// Generated by CoffeeScript 1.6.3
(function() {
  var corpus, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  corpus = root.corpus = "e2\ne2 d#2\ne2 d#2 e2\nb1\ne2 d#2 e2 b1\ne2 d#2 e2 b1 d2 c2\ne2 d#2 e2 d#2 e2 b1 d2 c2\nc1 e1\nb1 e1\na1\na1 c1 e1\na1 c1 e1 a1\nb1 e1 g#1 b1\na1 c1 e1 a1 b1 e1 g#1 b1\ne2 d#2 e2 d#2 e2 b1 d2 c2 a1 c1 e1 a1\ne2 d#2 e2 d#2 e2 b1 d2 c2 a1 c1 e1 a1 b1 e1 g#1 b1\nyou have finished the task. return to skilltree.html";

}).call(this);
