// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var corpus, root;



  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  corpus = root.corpus = "e2 d#2 e2 d#2 e2 b1 d2 c2 a1 c1 e1 a1 b1 e1 g#1 b1 c2 e1 e2 d#2 e2 d#2 e2 b1 d2 c2 a1 c1 e1 a1\ncongratulations you have finished this milestone! return to the skill tree.";

}).call(this);
