// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var main, root, toHitCode;



  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  toHitCode = root.toHitCode = function(taskname) {
    var char, hash, i, _i, _ref;
    hash = 0;
    if (taskname.length === 0) {
      return hash;
    }
    for (i = _i = 0, _ref = taskname.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      char = taskname.charCodeAt(i);
      hash = ((hash << 5) - hash) + char;
      hash |= 0;
    }
    if (hash < 0) {
      return Math.floor(-hash / 4096);
    }
    return Math.floor(hash / 4096);
  };

  main = function() {
    console.log(process.argv[2]);
    return console.log(toHitCode(process.argv[2]));
  };

  if (require.main === module) {
    main();
  }

}).call(this);
