// Generated by CoffeeScript 1.6.3
(function() {
  var corpus, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  corpus = root.corpus = "d1 d1 e1 d1 c1\ne1 e1 e1 e1\ne1 d1 c1 d1 e1 e1 e1 e1\ne1 e1 e1 e1 d1 d1 e1 d1 c1\ne1 g1 g1 e1 d1 c1 d1\nd1 d1 d1 e1 g1 g1 e1 d1 c1 d1\ne1 g1 g1 e1 d1 c1 d1 e1 e1 e1 e1\ne1 e1 e1 d1 d1 d1 e1 g1 g1 e1 d1 c1 d1\nd1 d1 d1 e1 g1 g1 e1 d1 c1 d1 e1 e1 e1 e1\ne1 d1 c1 d1 e1 e1 e1 d1 d1 d1 e1 g1 g1 e1 d1 c1 d1\ne1 d1 c1 d1 e1 e1 e1 d1 d1 d1 e1 g1 g1 e1 d1 c1 d1 e1 e1 e1 e1\ne1 d1 c1 d1 e1 e1 e1 e1 d1 d1 e1 d1 c1\ne1 g1 g1 e1 d1 c1 d1 e1 e1 e1 e1 d1 d1 e1 d1 c1\ne1 e1 e1 d1 d1 d1 e1 g1 g1 e1 d1 c1 d1 e1 e1 e1 e1 d1 d1 e1 d1 c1\ne1 d1 c1 d1 e1 e1 e1 d1 d1 d1 e1 g1 g1 e1 d1 c1 d1 e1 e1 e1 e1 d1 d1 e1 d1 c1\ncongratulations you have finished this milestone! return to the skill tree.";

}).call(this);
