// Generated by CoffeeScript 1.6.3
(function() {
  var documentReady, root, toHitCode, validateForm;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.taskname = '${taskname}';

  if (root.taskname.indexOf('taskname') !== -1) {
    root.taskname = 'foobarrr';
  }

  toHitCode = function(taskname) {
    var output, x, _i, _len;
    output = 0;
    for (_i = 0, _len = taskname.length; _i < _len; _i++) {
      x = taskname[_i];
      output += x.charCodeAt(0);
    }
    return output;
  };

  root.validateForm = validateForm = function() {
    var expected_hitcode, hitcode;
    expected_hitcode = toHitCode(root.taskname).toString();
    hitcode = document.getElementById('hitcode').value.trim();
    if (hitcode !== expected_hitcode) {
      alert('the hitcode you input: "' + hitcode + '" is not correct');
      return false;
    }
    return true;
  };

  documentReady = function() {
    var submitButton;
    submitButton = document.getElementById('submitButton');
    return submitButton.onclick = 'return validateForm()';
  };

  document.onreadystatechange = function() {
    if (document.readyState === 'complete') {
      return documentReady();
    }
  };

}).call(this);
