// Generated by CoffeeScript 1.6.3
(function() {
  var addMilestones, milestone_fullnames, milestone_list, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  milestone_list = ['mary_had_a_little_lamb_chorus', 'mary_had_a_little_lamb_full', 'fur_elise_chorus', 'fur_elise_full', 'fur_elise_complete'];

  milestone_fullnames = {
    mary_had_a_little_lamb_chorus: 'Mary Had a Little Lamb (chorus only)',
    mary_had_a_little_lamb_full: 'Mary Had a Little Lamb (full lesson)',
    fur_elise_chorus: 'Fur Elise (chorus only)',
    fur_elise_full: 'Fur Elise (full lesson)',
    fur_elise_complete: 'Fur Elise (complete song)'
  };

  addMilestones = function() {
    var milestone, milestone_button, milestone_name, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = milestone_list.length; _i < _len; _i++) {
      milestone = milestone_list[_i];
      milestone_name = milestone_fullnames[milestone];
      milestone_button = $('<button>');
      milestone_button.attr('onclick', "window.location = 'practice?songname=" + milestone + "#0'");
      milestone_button.attr('type', 'button');
      milestone_button.addClass('btn btn-default btn-lg');
      milestone_button.css('width', '100%');
      milestone_button.css('text-align', 'left');
      milestone_button.append($('<span>').addClass('glyphicon glyphicon-music'));
      milestone_button.append(' ');
      milestone_button.append(milestone_name);
      _results.push($('#milestones').append(milestone_button));
    }
    return _results;
  };

  $(document).ready(function() {
    addMilestones();
    return console.log('stuff happened!');
  });

}).call(this);
